# backend/Dockerfile

# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the dependencies file to the working directory
COPY requirements.txt ./

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Expose port 8000 to the outside world
EXPOSE 8000

# Define the default command to run when the container starts
CMD ["gunicorn", "my_project.wsgi:application", "--bind", "0.0.0.0:8000"]
