version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    command: gunicorn my_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env
